import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/header/Header";
import FilterSidebar from "../../components/filter-sidebar/FilterSidebar";
import { Providers } from "../../providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Showtime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Header />
          <FilterSidebar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
